# Generated by Django 5.1.2 on 2025-06-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='reddit_token',
            new_name='facebook_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
