# Generated by Django 5.1.2 on 2025-06-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_reddit_token_profile_facebook_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='unverified_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
