# Generated by Django 5.1.2 on 2025-07-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_facebook_token_profile_twitter_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_temp_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
