# Generated by Django 5.1.2 on 2025-07-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_otp_temp_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instagram_token',
            new_name='reddit_access_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='reddit_refresh_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
