# Generated by Django 5.1.2 on 2025-07-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_instagram_token_profile_reddit_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reddit_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
