# Generated by Django 5.1.2 on 2025-07-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_youtube_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reddit_token_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_token_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='profile_pics/'),
        ),
    ]
