# Generated by Django 5.2.4 on 2025-08-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_discord_bot_token_profile_discord_guild_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='snapchat_access_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='snapchat_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
