# Generated by Django 5.2.4 on 2025-08-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_profile_snapchat_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='snapchat_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='snapchat_access_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
