# Generated by Django 5.2.4 on 2025-09-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_profile_snapchat_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discord_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
