# Generated by Django 5.2.4 on 2025-09-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_profile_discord_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='discord_bot_token',
            new_name='facebook_token',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='discord_guild_id',
            new_name='fb_hometown',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='discord_token',
            new_name='fb_location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='discord_token_updated_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pinterest_access_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pinterest_refresh_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pinterest_token_updated_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pinterest_username',
        ),
        migrations.AddField(
            model_name='profile',
            name='fb_age_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fb_birthday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fb_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fb_friends',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fb_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fb_likes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fb_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fb_photos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fb_posts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fb_videos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
